settings:
  application:
    model: dev
    host: 0.0.0.0
    port: 8008
  database:
    # 数据库类型 mysql
    driver: mysql
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    source: root:insur132@tcp(127.0.0.1:3306)/go_application?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  redis:
    addr: 127.0.0.1:6379